

import Header from "@/components/organisms/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/organisms/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} antialiased`}>
      <body>
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
